---

- name: Apply Baseline Configuration and Hardening to Linux Infrastructure
  hosts: ubuntuservers
  become: true # Run as sudo
  roles:
    - common
    - users
    - ssh
    - firewall
    - fail2ban