---
- name: Update all packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages to latest version
  ansible.builtin.apt:
    dpkg_options: "force-confdef,force-confold" # Bypass user input 
    upgrade: dist

- name: Install essential baseline packages
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - htop
      - git
      - net-tools
    state: present

- name: Set system timezone to UTC
  community.general.timezone:
    name: UTC